binast/binjs-ref

package-lock.json, package.json
=> pruning and updating package json

tests/test_roundtrip.rs
We have trouble with Travis, as we're spamming the logs a bit too much. This patch limits logging to mostly printing simple "." instead of entire messages. This indicates progress, so Travis won't kill us, but hopefully without
going past the 4Mb barrier.
=> test_roundtrip: limiting logging

README.md
This would have saved me some time :) Might help others too
=> Update install instructions to include making rust nightly the default

crates/binjs_generate_library/src/lib.rs
Changed it to use vector of tuple, instead of HashMap
=> Fix the field order in Visitor (fixes #148)

crates/binjs_es6/src/io.rs, crates/binjs_es6/src/scopes.rs, crates/binjs_generate_library/src/lib.rs, crates/binjs_generic/src/io/decode.rs, crates/binjs_generic/src/io/encode.rs, crates/binjs_generic/src/pick.rs, crates/binjs_generic/src/syntax.rs, crates/binjs_io/src/io.rs, crates/binjs_io/src/multipart/read.rs, crates/binjs_io/src/multipart/write.rs, crates/binjs_io/src/simple.rs, crates/binjs_meta/src/export.rs, crates/binjs_meta/src/import.rs, crates/binjs_meta/src/spec.rs, package-lock.json, spec/es6.webidl, src/source/shift.rs
corresponds to https://github.com/binast/ecmascript-binary-ast/pull/52
@Yoric, can you review?
also, if I have multiple patches for different issues,
is it better posting PRs one by one, or put all of them into single PR ?
=> Add AssertedPositionalParameterName, AssertedRestParameterName, and AssertedParameterName (fixes #152)

crates/binjs_es6/src/scopes.rs
just removed function name from param scope.
=> Remove function expression name from parameter scope (fixes #151)

src/bin/decode.rs, src/bin/encode.rs
Just added quiet mode, as a preparation for https://github.com/binast/binjs-ref/issues/166
=> Add quiet mode

Cargo.toml, crates/binjs_es6/Cargo.toml, crates/binjs_generate_library/Cargo.toml, crates/binjs_generic/Cargo.toml, crates/binjs_meta/Cargo.toml
This should hopesfully help with petgraph.
=> Moved to webidl 0.7

crates/binjs_meta/src/spec.rs
Since this would be useful for SpiderMonkey, let's make this work!
=> NodeName::to_rc_string, FieldName::to_rc_string

crates/binjs_shared/src/json_conversion.rs
given `JSON.as_f64()` cannot be used, I've prepared another hacky workaround that uses Rust's `String::parse`, which keeps the precision for #191 case.
actually this is very redundant in term of operations (extra turnaround between number -> string -> number), but I guess this is the simplest workaround in term of the code change.
how do you think?
=> Use String::parse to convert JSON::Number to f64 (fixes #191)

crates/binjs_io/Cargo.toml, crates/binjs_io/src/entropy/dictionary.rs, crates/binjs_io/src/entropy/mod.rs, crates/binjs_io/src/entropy/predict.rs, crates/binjs_io/src/entropy/write.rs, src/bin/generate_dictionary.rs, tests/test_dictionary_builder.rs
=> Entropy strings

crates/binjs_io/src/entropy/predict.rs
Our set of probabilities was issued in an arbitrary order. We want to
ensure that probabilities match their symbol. Doing otherwise doesn't
break (de)compression but hurts compression levels a lot.
As an example (on the experimental entropy-window branch), frameworks
Before this patch:
property keys: 97217 bytes, 52193 symbols (14.90 bits/symbol)
65.19% Hits: 63751 bytes, 34026 symbols (14.99 bits/symbol)
34.81% Misses: 33375 bytes, 18167 symbols (14.70 bits/symbol)
identifier names: 304404 bytes, 166544 symbols (14.62 bits/symbol)
94.12% Hits: 287173 bytes, 156746 symbols (14.66 bits/symbol)
5.88% Misses: 17217 bytes, 9798 symbols (14.06 bits/symbol)
string literals: 46387 bytes, 26175 symbols (14.18 bits/symbol)
42.47% Hits: 19714 bytes, 11116 symbols (14.19 bits/symbol)
57.53% Misses: …
=> Sorting is important not only for symbol indices but also for probabilities

Cargo.toml, build.rs, src/source/shift.rs
Please see commit messages for details.
=> Fix building on Windows

crates/binjs_generic/src/syntax.rs, crates/binjs_io/Cargo.toml, crates/binjs_io/src/bytes/compress.rs, crates/binjs_io/src/bytes/float.rs, crates/binjs_io/src/bytes/varnum.rs, crates/binjs_io/src/io/content.rs, crates/binjs_io/src/lib.rs, crates/binjs_shared/src/ast.rs, crates/binjs_shared/src/shared_string.rs
Ok, let's start landing entropy 0.2!
=> Landing Entropy 0.2 (first part)

crates/binjs_io/src/entropy/read/mod.rs, crates/binjs_io/src/entropy/read/prelude_decoders.rs
Fixes for two issues detected thanks to #272.
=> Fixes for the decoder

Cargo.toml, benches/bench_fb.rs, crates/binjs_generate_library/Cargo.toml, crates/binjs_generate_library/src/lib.rs, crates/binjs_generic/Cargo.toml, crates/binjs_generic/src/lib.rs, crates/binjs_io/Cargo.toml, crates/binjs_io/src/lib.rs, crates/binjs_meta/Cargo.toml, crates/binjs_meta/src/util.rs, crates/binjs_shared/Cargo.toml, crates/binjs_shared/src/lib.rs, examples/compare_compression.rs, src/bin/convert_from_json.rs, src/bin/encode.rs, src/bin/generate_dictionary.rs, src/lib.rs, tests/test_roundtrip.rs
In this PR I tried my best to find and remove or categorise unused deps, and also upgraded transitive dependencies of `test-logger` by forking it here https://github.com/RReverser/test-logger (they are pretty outdated and cause a lot of duplicates as you can see below, but the author haven't responded to my PR yet, so I think it's fine as-is).
For short summary, the diff of entire list of dependencies after this looks like this:
```diff
@@ -914,7 +804,6 @@ dependencies = [
[metadata]
"checksum Inflector 0.11.3 (registry+https://github.com/rust-lang/crates.io-index)" = "4467f98bb61f615f8273359bf1c989453dfc1ea4a45ae9298f1dcd0672febe5d"
"checksum adler32 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = "7e522997b529f05601e05166c07ed17789691f562762c7f3b987263d2dedee5c" …
```
=> Cleanup deps

Cargo.toml, tests/test_external_roundtrip.rs
This should catch any regression to https://github.com/binast/binjs-ref/issues/270.
If this works, I'll complete this with more tests.
=> Integration testing between binjs_decode and binjs_encode

tests/test_external_roundtrip.rs
This patch adds an external roundtrip test that builds and uses an external dictionary.
=> More external roundtrip tests

examples/investigate_streams.rs
This tool should help us determine which streams are most expensive in terms of disk usage.
=> New command-line tool: investigate_streams.

crates/binjs_io/Cargo.toml, crates/binjs_io/src/multipart/mod.rs, crates/binjs_io/src/simple.rs, examples/compare_compression.rs
=> Resolves #313 - Get rid of hardcoded path /tmp

benches/test.js
=> Remove unused benches/test.js

crates/binjs_es6/src/lazy.rs, crates/binjs_es6/src/scopes.rs, crates/binjs_generate_library/src/lib.rs, crates/binjs_io/src/entropy/mod.rs, crates/binjs_shared/src/lib.rs, crates/binjs_shared/src/shared_string.rs, tests/test_dictionary_builder.rs, tests/test_roundtrip.rs
This should simplify a bit the code.
Part on the ongoing work towards specializing for JSON.
=> Introducing trait WalkGuard

spec/entropy.md
This documentation/spec is very incomplete as of yet, but I'm planning to improve it gradually.
=> [Doc] Documenting a subset of the entropy 0.4 format

spec/context.md
> A file may contain one or more **Chunks**
Reflected to the grammar.
=> Require at least one chunk

src/bin/encode.rs, tests/data/misc/test.a.b.c.d.js, tests/test_external_roundtrip.rs
Replaces #408 
Could you please take a look @RReverser?
=> Refactor set extension

fbssdc/bpy.py
This will simplify generating large batches of tests.
=> bpy: Added a new subcommand encode-dir to encode entire directories

crates/binjs_meta/Cargo.toml
A distinct patch will handle the Node dependencies.
=> Issue #423 - Updating Rust dependencies and releasing new version

fbssdc/bpy.py
Use case: building a large corpus of samples for benchmarking purposes from a set of samples that may not be encodable.
=> bpy encode_dir may now skip errors and copy source files

.travis.yml
This should make error messages slightly easier to read.
=> Travis: Separating format check from build step

Cargo.toml, crates/binjs_generate_library/Cargo.toml, crates/binjs_generic/Cargo.toml, crates/binjs_io/Cargo.toml, crates/binjs_meta/Cargo.toml
Also remove the default features from Inflector since those are not used
=> Update all dependencies
