.travis.yml
This should help with https://github.com/binast/binjs-ref/pull/76 by making sure that Travis sees progress even with long-running test_roundtrip.
=> Travis: Don't capture test output

crates/binjs_io/src/multipart/mod.rs
In multipart document, "node name" seems to be missing in the grammar table, compared to the implementation,
so added it to the document.
also, I cannot find the implementation for reading fields.
I haven't touched that document tho.
=> Add missing node name into multipart grammar document

crates/binjs_es6/src/scopes.rs
There are two bugs here:
First, catch blocks had mismatched stack pushes and pops, leading to total confusion.
Second, we were blurring all seen names into flat levels, meaning that we couldn't tell sibling uses and bindings from nested uses and bindings.
Previously,
```
var a;
(function () {
a;
{
let a;
}
})
```
did not mark the var as closed over, even though it clearly is, since it saw the sibling binding.
=> Nested scope closure

crates/binjs_meta/src/util.rs
Corresponds to the function added in https://bugzilla.mozilla.org/show_bug.cgi?id=1472101 , ported to binjs_meta/src/util.rs
I'll remove the one in m-c once this is merged and released.
=> Add ToStr.newline_if_not_empty

crates/binjs_es6/src/lazy.rs, crates/binjs_es6/src/lib.rs, crates/binjs_es6/src/scopes.rs, crates/binjs_generate_library/src/lib.rs, crates/binjs_io/src/multipart/read.rs, crates/binjs_io/src/multipart/write.rs, crates/binjs_meta/src/export.rs, crates/binjs_meta/src/import.rs, crates/binjs_meta/src/spec.rs, spec/es6.webidl, src/bin/encode.rs, src/source/shift.rs, tests/test_roundtrip.rs
to be clear, I don't intend do land this immediately.
discussion is here: https://github.com/orgs/binast/teams/binast-core/discussions/7
this updates the in-tree idl and corresponding parts to match to the spec at the point of Jun 28.
https://github.com/binast/ecmascript-binary-ast/commits/spec-draft
The main changes are:
- AssertedDeclaredName/AssertedBoundName + AssertedDeclaredKind for scopes
- Skippable interface to Lazy field
- skip/skipped implicit fields are removed, and {fieldname}_skip field is inserted before the lazy field, which has offset
- separate Function and Contents
- separate ArrowExpression for FunctionBody and Expression
- scope is no more optional
- when converting from Shift's JSON, dummy scope object is created
- version number is bumped
=> Update idl to match ecmascript-binary-ast f2bbb2a69fa0d37a36efa70716cf7d6e5fe10851

crates/binjs_es6/src/lazy.rs, spec/es6.webidl, src/source/shift.rs
corresponds to binast/ecmascript-binary-ast#55
dummy_parameter_scope is modified to return both scope and length fields.
=> Add length field to functions (fixes #153)

crates/binjs_es6/src/io.rs, crates/binjs_generate_library/src/lib.rs, crates/binjs_generic/src/io/decode.rs, crates/binjs_generic/src/io/encode.rs, crates/binjs_io/src/entropy/mod.rs, crates/binjs_io/src/entropy/model.rs, crates/binjs_io/src/entropy/predict.rs, crates/binjs_io/src/entropy/read.rs, crates/binjs_io/src/entropy/tree.rs, crates/binjs_io/src/entropy/write.rs, crates/binjs_io/src/io.rs, crates/binjs_io/src/multipart/mod.rs, crates/binjs_io/src/multipart/read.rs, crates/binjs_io/src/multipart/write.rs, crates/binjs_io/src/simple.rs, crates/binjs_io/src/xml.rs, crates/binjs_shared/src/lib.rs, crates/binjs_shared/src/shared_string.rs
More work on using `SharedString` everywhere and avoiding copies.
=> Consolidating shared strings

crates/binjs_io/src/multipart/write.rs
Defined the order between the table entries with the same number of uses,
so that the order between them is fixed in the file
=> Order table entries with same number of use by data itself (fixes #171)

src/bin/decode.rs, src/bin/encode.rs, src/source/shift.rs
I'm not sure how to handle patch stack on github, anyway here's the patch for command-line filter mode, on https://github.com/binast/binjs-ref/pull/167
=> Add command-line filter mode (fixes #166) 

crates/binjs_io/src/lib.rs, examples/compare_compression.rs, examples/generate.rs, examples/roundtrip.rs, src/bin/encode.rs
given prividers are subsubcommand, we should first check the `advanced` subcommand there and check against `matches` for the subcommand.
=> Fix advanced subsubcommand (fixes #178)

src/util/mod.rs
`lalrpop` has some transitive dependency that still uses `rand 0.5.5` which causes problem while doing WASM compilation.
Also it is good for WASM to use `thread_rng` instead of `OsRng` here.
=> move to thread rng instead of OsRng for WASM

crates/binjs_es6/src/io.rs, crates/binjs_generate_library/src/lib.rs, crates/binjs_generic/src/io/decode.rs, crates/binjs_io/src/entropy/read.rs, crates/binjs_io/src/io/mod.rs, crates/binjs_io/src/multipart/mod.rs, crates/binjs_io/src/multipart/read.rs, crates/binjs_io/src/simple.rs
(possibly conflict with some changes in other PR)
having separate struct to track the end of list/tuple is hard to manage, because of ownership,
and I think just introducing enter/leave is sufficient for existing case.
Removed Guard structs/traits, and replaced it with {enter,leave}_{list,tagged_tuple,untagged_tuple}_at.
let me know entropy is going to introduce another guard and it conflicts with this.
will ask review after test.
=> Use {enter,exit}_* in and remove Guard from TokenReader.

crates/binjs_generate_library/src/lib.rs, crates/binjs_io/src/simple.rs, crates/binjs_meta/src/util.rs, rust-toolchain, tests/test_roundtrip.rs
Fix warnings reported by Rust and also set default toolchain to nightly for rustup (since code is using nightly-specific `#![feature(...)]`).
=> Fix warnings

.travis.yml, crates/binjs_es6/src/lib.rs, crates/binjs_es6/src/scopes.rs, crates/binjs_generate_library/src/lib.rs, crates/binjs_generic/src/lib.rs, crates/binjs_io/src/lib.rs, rust-toolchain, src/lib.rs
Turns out, we don't really need the nightly features we've been relying on, so this should simplify average usage without opting in to quirks of nightly Rust.
=> Support stable Rust and Node.js

Cargo.toml, crates/binjs_es6/Cargo.toml, crates/binjs_es6/build.rs, crates/binjs_generate_library/Cargo.toml, crates/binjs_generate_library/examples/generate_library.rs, crates/binjs_generic/Cargo.toml, crates/binjs_generic/build.rs, crates/binjs_meta/Cargo.toml, crates/binjs_meta/examples/generate_spidermonkey.rs, crates/binjs_meta/src/import.rs, crates/binjs_meta/src/lib.rs
This should significantly improve compilation times because `webidl` has `lalrpop` as a dependency which is pretty heavy and blows them up, whereas `weedle` uses just `nom` and so parses with pretty much pure Rust.
Some reference results from my machine with `cargo clean && cargo build -j4 [--release]`:
|         | `webidl` | `weedle` | diff    | diff (%) |
| ------- | -------- | -------- | ------- | -------- |
| debug   | 2m 34s   | 2m 01s   | -0m 33s | -21%     |
| release | 5m 43s   | 4m 37s   | -1m 06s | -19%     |
Initially inspired by https://github.com/rustwasm/wasm-bindgen/pull/639 which performed a similar migration.
=> Migrate from webidl to weedle

Cargo.toml, benches/bench_fb.rs, benches/test.js, examples/compare_compression.rs, examples/generate.rs, package-lock.json, package.json, src/bin/decode.rs, src/bin/encode.rs, src/bin/generate_dictionary.rs, src/lib.rs, src/source/codegen.js, src/source/escape_wtf8.js, src/source/parse_file.js, src/source/parse_str.js, src/source/shift.rs, src/source/start-json-stream.js, tests/test_dictionary_builder.rs, tests/test_paths.rs, tests/test_roundtrip.rs
This series of commits first simplifies parsing benchmarking to a trivial case to more reliably measure just the overhead of Rust -> Node.js interaction since it's the main contributor to performance issues when invoking Shift tasks.
Then, it changes previous model of running Node.js with given script as an input for each task, to spawning long-term Node.js "services" instead, with each script living in a separate file.
Before Node.js would just accept and spit either raw string or JSON. Now, all the communication is done via ND-JSON (newline-delimited JSON) streams, using the stdin/stdout pipes of the spawned process.
Also, before parsing or other errors would kill the process, dumping the error stack into stderr. This is fine for a single-run model, but not acceptable for long-living …
=> Performance: reuse Node.js instance for Shift tasks

crates/binjs_io/src/binjs_json/mod.rs, crates/binjs_io/src/entropy/mod.rs, crates/binjs_io/src/entropy/predict.rs, crates/binjs_io/src/lib.rs, crates/binjs_io/src/multipart/mod.rs, crates/binjs_io/src/simple.rs, crates/binjs_io/src/xml.rs, crates/binjs_shared/src/ast.rs, crates/binjs_shared/src/shared_string.rs, examples/compare_compression.rs, examples/generate.rs, src/bin/convert_from_json.rs, src/bin/decode.rs, src/bin/encode.rs, tests/test_dictionary_builder.rs
This finishes connecting all the bits and pieces of Entropy 0.3.
With this PR, the compressor can finally compress data whose grammar constructions do not show up in the samples. In particular, this means that we can (poorly) compress without dictionary.
=> Resolve #249 - Entropy 0.3 - the rest

crates/binjs_io/src/binjs_json/read.rs, crates/binjs_io/src/binjs_json/write.rs, crates/binjs_io/src/escaped_wtf8.rs, crates/binjs_io/src/lib.rs, crates/binjs_io/src/multipart/read.rs
With this patch, the JSON format uses \uXXXX instead of internal escaped WTF-8.
The conversion is done on the entire stringified JSON, not for each string in the tree.
When reading, it first reads string from stream, and then convert \uXXXX with lone surrogate there and replaces them with internal escaped WTF-8 with `from_unicode_escape`, and then parse it.
When writing, it generates the tree and stringifies with raw internal escaped WTF-8, and then convert escaped WTF-8 with \uXXXX with `to_unicode_escape`, and write it.
those 2 operations are lossless as long as the input is in valid encoding, and it's JSON.
then, `to_unicode_escape` does the same thing as pre-existing `for_print`.
so just renamed it and changed the signature (`SharedString` => `String`).
it's still usable for debugging …
=> Support escaped WTF-8 in JSON format.

Cargo.toml, benches/bench_fb.rs
So... this was surprising and took me a long time to figure out, but apparently background Node.js processes affect bencher even if they're being shut down outside of the measurement code.
I don't know why exactly or how this happens, but even adding `.wait()` in drop code didn't help, so now I'm using a single shared parser for the `bench_parsing_reuse_parser`.
Before: 25,043,240 ns/iter (+/- 3,170,399)
After: 276,631 ns/iter (+/- 72,568)
=> Use lazy_static for parser reuse in benchmarks

crates/binjs_es6/src/io.rs, crates/binjs_io/src/entropy/dictionary.rs, crates/binjs_io/src/entropy/mod.rs, crates/binjs_io/src/entropy/read/content_decoders.rs, crates/binjs_io/src/entropy/read/mod.rs, crates/binjs_io/src/entropy/rw.rs, crates/binjs_io/src/entropy/write/mod.rs, crates/binjs_io/src/lib.rs, tests/test_dictionary_builder.rs
As it turns out, the most common value we fetch from a content stream is the "next in prelude". Experiments (see issue #298) indicate that reserving 0 for "next in prelude" improves compression of most streams. This is what this patch does.
=> Resolve #298 - In content streams, reserve 0 for "next in prelude"

crates/binjs_es6/build.rs, crates/binjs_generate_library/examples/generate_library.rs, crates/binjs_generic/build.rs, crates/binjs_meta/examples/generate_spidermonkey.rs, crates/binjs_meta/src/import.rs, crates/binjs_meta/src/spec.rs, spec/es6-extension.webidl
This patch adds support for extending es6.webidl with an additional file es6-extension.webidl. The role of that file is to modify the AST in a manner that is useful for *compression* but has no impact on visible *syntax and semantics* of the language. In other words, es6.webidl is meant to be part of the BinAST language specification, while es6-extension.webidl is meant to be part of the compression format.
The main objective of this patch is to let us adopt specialized compression dictionaries for e.g. JSON, arithmetic expressions, etc.
=> Issue #296 - Extending the webidl with a secondary file.

crates/binjs_es6/src/io.rs, crates/binjs_generate_library/src/lib.rs, crates/binjs_io/src/io/mod.rs, src/bin/generate_dictionary.rs, tests/test_dictionary_builder.rs, tests/test_paths.rs
In all cases `Serialization` already needs only a borrowed value, similarly to `serde::Serialize`, or an owned value of a primitive, which is easy and cheap to get from a borrow.
Hence, the definition can get simpler by always assuming a borrowed value of any type instead of requiring implementations with an explicit lifetime param.
=> Remove lifetime from Serialization trait

crates/binjs_io/src/entropy/mod.rs, crates/binjs_io/src/entropy/read/mod.rs, crates/binjs_io/src/entropy/write/mod.rs, crates/binjs_io/src/io/statistics.rs
General cleanup of `ContentInfo`.
=> Entropy 0.4 statistics cleanup

crates/binjs_io/Cargo.toml, crates/binjs_io/src/entropy/baseline.rs, crates/binjs_io/src/entropy/dictionary.rs, crates/binjs_io/src/entropy/predict.rs, crates/binjs_io/src/entropy/read/mod.rs, crates/binjs_io/src/entropy/write/mod.rs
For the ongoing work on sublanguages, we'll need the ability to switch between dictionaries and to share dictionary components
between predictors/tables. This patch prepares this work by removing much need for mutability in predictors and dictionaries,
and producing clean accessors for predictors/tables.
=> Rework predictors and Dictionary<> to minimize &mut requirements.

crates/binjs_io/Cargo.toml, crates/binjs_io/src/entropy/dictionary.rs, crates/binjs_io/src/entropy/predict.rs, crates/binjs_io/src/entropy/probabilities.rs, crates/binjs_io/src/entropy/read/mod.rs, crates/binjs_io/src/entropy/write/mod.rs
We put all the fields of `Dictionary` behind a `Rc<RefCell<>>`. This makes
a call to `Dictionary::clone` cheap, but more importantly, once we start
using dictionaries for sublanguages, this lets us share the elements
that need to be shared between the sublanguages.
=> Make it easier to share elements of a Dictionary.

src/bin/decode.rs
Without this, binjs_decode was failing with stack overflow on large-ish inputs.
=> Add thread stack size wrapper for binjs_decode

crates/binjs_es6/build.rs, crates/binjs_generate_library/examples/generate_library.rs, crates/binjs_generic/build.rs, crates/binjs_io/src/entropy/write/lazy_stream.rs, crates/binjs_io/src/entropy/write/mod.rs, crates/binjs_io/src/multipart/mod.rs, crates/binjs_io/src/simple.rs, crates/binjs_meta/examples/generate_spidermonkey.rs, examples/compare_compression.rs, examples/generate.rs, src/bin/decode.rs, src/bin/dump.rs, src/bin/encode.rs, src/bin/generate_dictionary.rs, tests/test_external_roundtrip.rs
These helpers simplify and improve readability of code around reading/writing whole files.
=> Use std::fs::{write, read_to_string} when possible

crates/binjs_io/src/entropy/dictionary.rs, crates/binjs_io/src/entropy/read/content_decoders.rs, crates/binjs_io/src/entropy/rw.rs, crates/binjs_io/src/entropy/write/mod.rs, crates/binjs_io/src/io/mod.rs, tests/test_dictionary_builder.rs
This applies the transformation presented in #304 to reduce the sparsity of shared indices. It improves compression by ~4.5%.
=> Resolve #304 - Reduce sparsity of shared indices

tests/test_external_roundtrip.rs
This tends to be useful in debugging of this test, even if a bit verbose (that part should be fixable by replacing `println!` in the codebase with `debug!` where possible).
=> Always print output from test_external_roundtrip

src/source/.prettierrc, src/source/codegen.js, src/source/from-shift.js, src/source/parse_file.js, src/source/parse_str.js, src/source/shift.rs, src/source/start-json-stream.js, src/source/to-shift.js
This is the first part of #342 that should make it easier to switch between JSON parsers (or avoid them altogether when used from WASM).
It's mostly manual line-by-line conversion with the exception of using a simpler syntax in JS where possible.
Tests seem to pass, but would love a careful look from someone else as manual conversions tend to be easily error-prone.
Angular parsing benchmark shows ~8% regression in parsing times, but I think we'll easily gain that back longer term by avoiding JSON AST.
=> Move FromShift conversion to JavaScript land

src/source/from-shift.js, src/source/start-json-stream.js
Basically I think it's right to do this first - we shouldn't be applying `escapeWTF8` on result of the codegen in the first place (or on error messages), only on string values in the AST.
This should partially help with #350 but will still need some of your changes in #351.
=> Apply escapeWTF8 only on strings in AST

src/source/from-shift.js, src/source/shift.rs, tests/data/misc/lone-surrogate.js, tests/test_roundtrip.rs
There were 2 issues:
- input is not unescaped in `codegen.js`
- so the output of `codegen` is escaped twice
- source is not unescaped before writing to file in `decode.rs`
- so the decoded file is still escaped twice
So:
- added `inputIsEscapedWTF8` parameter to `start-json-stream.js`
- if it's `true`, input is unescaped before handling
- use `inputIsEscapedWTF8` in `codegen.js`
- unescape the output of `Shift` in `decode.rs`
=> Unescape escaped WTF-8 properly in binjs_deode (fixes #350)

Cargo.toml, crates/binjs_io/src/entropy/mod.rs, examples/sample_directory.rs
This patch introduces examples/sample_directory.rs. This binary takes as argument a directory name
and a sampling factor `f` for the dictionary. From the directory, `f`% of the files are then used
to build a dictionary, while the rest of the files are compressed.
Display the compression results and, optionally, the list of worst offenders.
=> Issue 338 - Compare compression against a large sample

crates/binjs_es6/src/io.rs, crates/binjs_io/src/binjs_json/write.rs, crates/binjs_io/src/bytes/atoms.rs, crates/binjs_io/src/bytes/float.rs, crates/binjs_io/src/entropy/write/mod.rs, crates/binjs_io/src/simple.rs, crates/binjs_io/src/xml.rs
Before this, Encoder::encode was wrapping a heap-allocated data into another heap-allocated dynamic trait object.
This is inefficient and unnecessary, so I changed encoders to just return plain Box<[u8]> data.
=> Eliminate dynamic trait object in Encoder::encode

benches/bench.rs, crates/binjs_shared/src/json_conversion.rs, examples/compare_compression.rs, examples/generate.rs, examples/sample_directory.rs, src/bin/decode.rs, src/bin/encode.rs, src/bin/generate_dictionary.rs, src/lib.rs, src/source/parser.rs, src/source/shift.rs, tests/test_dictionary_builder.rs, tests/test_paths.rs, tests/test_roundtrip.rs
This makes parser and codegen both easier to use and maintain, since the primary public API doesn't rely on a specific JSON parser implementation anymore.
=>  Abstract away AST <-> JSON conversions in Rust

tests/test_roundtrip.rs
- Chose only 4 files from dataset (2 from facebook, 2 from framework).
- Removed randomness
- Test files are still there
=> Run only subset of testcases in roundtrip (fixes #200)

crates/binjs_es6/src/lazy.rs, crates/binjs_es6/src/scopes.rs, crates/binjs_generate_library/src/lib.rs, tests/test_dictionary_builder.rs, tests/test_roundtrip.rs
This patch contains two small changes for the AST visitor:
- guards now take as argument the visitor, instead of no argument;
- implementing a method `ViewMut*::steal()` to recover the underlying value.
=> Preparing AST visitor for injection of scoped dictionary changes.

crates/binjs_io/src/entropy/mod.rs, crates/binjs_shared/src/lib.rs, crates/binjs_shared/src/shared_string.rs
Documentation generated by rustdoc ignores comments such as
```rust
/// Documentation
use_a_macro_to_declare_a_type_or_value!(...)
```
This patch tweaks our macro declarations to recognize documentation
comments and turn them into actual comments recognized by rustdoc.
As a side-effect, it fixes warnings on Rust nightly.
=> Move comments inside macros.

crates/binjs_es6/src/lazy.rs, crates/binjs_es6/src/scopes.rs, crates/binjs_generate_library/src/lib.rs, tests/test_dictionary_builder.rs, tests/test_roundtrip.rs
The ViewMut* mechanism lets clients *steal* subnodes of a tree for rewriting purposes.
To steal a subnode, it needs to create a `Default::default()` node, but this can lead
to infinite recursions if the default case happens to rely upon a node of the same type.
This patch introduces `Foo::BinASTStolen` for all AST enums `Foo`, which serves to
generate the default node, and serves whenever we steal a node.
=> Introducing a new enum variant BinASTStolen to represent stolen AST nodes

src/bin/generate_dictionary.rs
Set the default dictionary depth to 2 in generate_dictionary . issue 363
=> Set the default dictionary depth to 2 in generate_dictionary . issue 363

crates/binjs_es6/Cargo.toml, crates/binjs_es6/src/lazy.rs, crates/binjs_es6/src/lib.rs, crates/binjs_es6/src/scopes.rs, crates/binjs_es6/src/sublanguages.rs, crates/binjs_io/src/entropy/mod.rs, crates/binjs_io/src/lib.rs, crates/binjs_shared/src/lib.rs, examples/compare_compression.rs, examples/generate.rs, examples/sample_directory.rs, src/bin/encode.rs, src/bin/generate_dictionary.rs, tests/test_dictionary_builder.rs, tests/test_paths.rs, tests/test_roundtrip.rs
We don't necessarily want to panic whenever we cannot enrich a file. This patch is a first step towards converting our Enrich mechanism to something that bails out gracefully whenever it encounters an error.
=> Making annotations more robust

spec/context.md
Copied entropy.md to context.md (temporary name), and modified some strings to make the implementation simpler.
the format itself is still for entropy, and contains unnecessary parts for the new format.
those parts will be removed/changed once we get the code.
=> Create template for context-0.2 documentation as a copy of entropy.md

crates/binjs_io/src/bytes/decoders.rs, crates/binjs_io/src/bytes/mod.rs, crates/binjs_io/src/bytes/strings.rs, crates/binjs_io/src/context/mod.rs, crates/binjs_io/src/context/prelude.rs, crates/binjs_io/src/entropy/read/mod.rs, crates/binjs_io/src/entropy/read/prelude_decoders.rs, crates/binjs_io/src/entropy/util.rs, crates/binjs_io/src/lib.rs
This patch adds a PreludeDecoder for Context 0.2 and exposes to Context 0.2
the other decoders developed for Entropy 0.4 and that may be reused as such in Context 0.2.
=> Context 0.2: Prelude decoder

crates/binjs_generate_library/src/lib.rs
This fixes duplicate "type" keys in JSON output (--show-ast or --print-json) which are caused by the fact that structs already serialise their own tags.
=> Omit `"type"` on enums

crates/binjs_es6/src/scopes.rs, tests/data/scope/function_declaration.js, tests/test_roundtrip.rs
exit_binding_identifier contains a hard-coded list of nodes that represent
functions. This is hardly ideal (perhaps we should somehow put this in the webidl?)
and at some point, we failed to update this list, causing the bug.
=> Resolve #406 - exit_binding_identifier now handles lazy functions

crates/binjs_es6/src/sublanguages.rs, crates/binjs_io/src/lib.rs, crates/binjs_meta/Cargo.toml, crates/binjs_meta/src/export.rs
Currently, `TypeName` produces sum names that can change at each build. Making the order explicit.
=> Making TypeName more reproducible

crates/binjs_meta/src/export.rs, crates/binjs_meta/src/import.rs, crates/binjs_meta/src/util.rs
Building with mozilla-central fails because of these warnings about unnecessary `mut` (that I think treated as error there).
=> Fix warning about unnecessary mut

crates/binjs_es6/src/scopes.rs, crates/binjs_io/src/binjs_json/write.rs, crates/binjs_io/src/bytes/compress.rs, crates/binjs_io/src/entropy/dictionary.rs, crates/binjs_io/src/entropy/mod.rs, crates/binjs_io/src/entropy/write/mod.rs, crates/binjs_io/src/escaped_wtf8.rs, crates/binjs_io/src/io/deprecated.rs, crates/binjs_io/src/io/mod.rs, crates/binjs_io/src/lib.rs, crates/binjs_io/src/multipart/mod.rs, src/bin/decode.rs
- a few instances of `mut` are now unnecessary;
- `dyn` is now required for trait objects;
- a few cases of duplicate `use`;
- `..=` replaces `...`.
=> Fixing warnings

crates/binjs_io/src/entropy/format.rs
Apparently, we've had a bad link in documentation forever.
=> Fix: Docbuild

fbssdc/format.md
This is the pdf written by @dominiccooney, ported to markdown, with minor reformatting tweaks (mainly to work around lack of subscript/superscript).
Barring any error, there should be no change to the content, with the exception of the line 36, which introduces syntactic conventions.
Once we have this, I'm planning to remove the section "Suggested improvements" and turn it into a list of github issues.
=> Documenting Context 0.1

crates/binjs_meta/Cargo.toml, crates/binjs_meta/src/import.rs
This changes the dependency from nom4 to nom5 which
is helpful for avoiding duplication in mozilla-central
=> Update to weedle 0.11
